import { Messages } from "../../messages.js";

// 清单直接放在代码中, 避免运行时下载, 内容来自检查过的 resources/minecraft-26.2.json
export const VANILLA_BLOCK_TAGS = [
  "minecraft:acacia_logs",
  "minecraft:air",
  "minecraft:all_hanging_signs",
  "minecraft:all_signs",
  "minecraft:ancient_city_replaceable",
  "minecraft:animals_spawnable_on",
  "minecraft:anvil",
  "minecraft:armadillo_spawnable_on",
  "minecraft:axolotls_spawnable_on",
  "minecraft:azalea_grows_on",
  "minecraft:azalea_root_replaceable",
  "minecraft:badlands_terracotta",
  "minecraft:bamboo_blocks",
  "minecraft:banners",
  "minecraft:bars",
  "minecraft:base_stone_nether",
  "minecraft:base_stone_overworld",
  "minecraft:bats_spawnable_on",
  "minecraft:beacon_base_blocks",
  "minecraft:beds",
  "minecraft:bee_attractive",
  "minecraft:bee_growables",
  "minecraft:beehives",
  "minecraft:beneath_bamboo_podzol_replaceable",
  "minecraft:beneath_tree_podzol_replaceable",
  "minecraft:birch_logs",
  "minecraft:blocks_wind_charge_explosions",
  "minecraft:buttons",
  "minecraft:camel_sand_step_sound_blocks",
  "minecraft:camels_spawnable_on",
  "minecraft:campfires",
  "minecraft:can_glide_through",
  "minecraft:candle_cakes",
  "minecraft:candles",
  "minecraft:cannot_replace_below_tree_trunk",
  "minecraft:cannot_support_kelp",
  "minecraft:cannot_support_seagrass",
  "minecraft:cannot_support_snow_layer",
  "minecraft:cauldrons",
  "minecraft:causes_continuous_geyser_eruptions",
  "minecraft:causes_periodic_geyser_eruptions",
  "minecraft:cave_vines",
  "minecraft:ceiling_hanging_signs",
  "minecraft:chains",
  "minecraft:cherry_logs",
  "minecraft:climbable",
  "minecraft:coal_ores",
  "minecraft:combination_step_sound_blocks",
  "minecraft:completes_find_tree_tutorial",
  "minecraft:concrete",
  "minecraft:concrete_powders",
  "minecraft:convertable_to_mud",
  "minecraft:copper",
  "minecraft:copper_chests",
  "minecraft:copper_golem_statues",
  "minecraft:copper_ores",
  "minecraft:coral_blocks",
  "minecraft:coral_plants",
  "minecraft:corals",
  "minecraft:crimson_stems",
  "minecraft:crops",
  "minecraft:crystal_sound_blocks",
  "minecraft:dampens_vibrations",
  "minecraft:dark_oak_logs",
  "minecraft:deepslate_ore_replaceables",
  "minecraft:default_immune_to",
  "minecraft:diamond_ores",
  "minecraft:dirt",
  "minecraft:does_not_block_hoppers",
  "minecraft:doors",
  "minecraft:dragon_immune",
  "minecraft:dragon_transparent",
  "minecraft:dripstone_replaceable_blocks",
  "minecraft:edible_for_sheep",
  "minecraft:emerald_ores",
  "minecraft:enables_bubble_column_drag_down",
  "minecraft:enables_bubble_column_push_up",
  "minecraft:enchantment_power_provider",
  "minecraft:enchantment_power_transmitter",
  "minecraft:enderman_holdable",
  "minecraft:fall_damage_resetting",
  "minecraft:features_cannot_replace",
  "minecraft:fence_gates",
  "minecraft:fences",
  "minecraft:fire",
  "minecraft:flower_pots",
  "minecraft:flowers",
  "minecraft:forest_rock_can_place_on",
  "minecraft:fox_immune_to",
  "minecraft:foxes_spawnable_on",
  "minecraft:frog_prefer_jump_to",
  "minecraft:frogs_spawnable_on",
  "minecraft:geode_invalid_blocks",
  "minecraft:glazed_terracotta",
  "minecraft:goats_spawnable_on",
  "minecraft:gold_ores",
  "minecraft:grass_blocks",
  "minecraft:grows_crops",
  "minecraft:guarded_by_piglins",
  "minecraft:happy_ghast_avoids",
  "minecraft:hoglin_repellents",
  "minecraft:huge_brown_mushroom_can_place_on",
  "minecraft:huge_red_mushroom_can_place_on",
  "minecraft:ice",
  "minecraft:ice_spike_replaceable",
  "minecraft:impermeable",
  "minecraft:incorrect_for_copper_tool",
  "minecraft:incorrect_for_diamond_tool",
  "minecraft:incorrect_for_gold_tool",
  "minecraft:incorrect_for_iron_tool",
  "minecraft:incorrect_for_netherite_tool",
  "minecraft:incorrect_for_stone_tool",
  "minecraft:incorrect_for_wooden_tool",
  "minecraft:infiniburn_end",
  "minecraft:infiniburn_nether",
  "minecraft:infiniburn_overworld",
  "minecraft:inside_step_sound_blocks",
  "minecraft:invalid_spawn_inside",
  "minecraft:iron_ores",
  "minecraft:jungle_logs",
  "minecraft:lanterns",
  "minecraft:lapis_ores",
  "minecraft:lava_pool_stone_cannot_replace",
  "minecraft:leaves",
  "minecraft:lightning_rods",
  "minecraft:logs",
  "minecraft:logs_that_burn",
  "minecraft:lush_ground_replaceable",
  "minecraft:maintains_farmland",
  "minecraft:mangrove_logs",
  "minecraft:mangrove_logs_can_grow_through",
  "minecraft:mangrove_roots_can_grow_through",
  "minecraft:mineable/axe",
  "minecraft:mineable/hoe",
  "minecraft:mineable/pickaxe",
  "minecraft:mineable/shovel",
  "minecraft:mob_interactable_doors",
  "minecraft:mooshrooms_spawnable_on",
  "minecraft:moss_blocks",
  "minecraft:moss_replaceable",
  "minecraft:mud",
  "minecraft:needs_diamond_tool",
  "minecraft:needs_iron_tool",
  "minecraft:needs_stone_tool",
  "minecraft:nether_carver_replaceables",
  "minecraft:nylium",
  "minecraft:oak_logs",
  "minecraft:occludes_vibration_signals",
  "minecraft:overrides_mushroom_light_requirement",
  "minecraft:overworld_carver_replaceables",
  "minecraft:overworld_natural_logs",
  "minecraft:pale_oak_logs",
  "minecraft:parrots_spawnable_on",
  "minecraft:piglin_repellents",
  "minecraft:planks",
  "minecraft:polar_bear_immune_to",
  "minecraft:polar_bears_spawnable_on_alternate",
  "minecraft:portals",
  "minecraft:pressure_plates",
  "minecraft:prevent_mob_spawning_inside",
  "minecraft:prevents_nearby_leaf_decay",
  "minecraft:rabbits_spawnable_on",
  "minecraft:rails",
  "minecraft:redstone_ores",
  "minecraft:replaceable",
  "minecraft:replaceable_by_mushrooms",
  "minecraft:replaceable_by_trees",
  "minecraft:sand",
  "minecraft:saplings",
  "minecraft:sculk_replaceable",
  "minecraft:sculk_replaceable_world_gen",
  "minecraft:shears_extreme_breaking_speed",
  "minecraft:shears_major_breaking_speed",
  "minecraft:shears_minor_breaking_speed",
  "minecraft:shulker_boxes",
  "minecraft:signs",
  "minecraft:slabs",
  "minecraft:small_flowers",
  "minecraft:smelts_to_glass",
  "minecraft:snaps_goat_horn",
  "minecraft:sniffer_diggable_block",
  "minecraft:sniffer_egg_hatch_boost",
  "minecraft:snow",
  "minecraft:snow_golem_immune_to",
  "minecraft:soul_fire_base_blocks",
  "minecraft:soul_speed_blocks",
  "minecraft:speleothems",
  "minecraft:spruce_logs",
  "minecraft:stairs",
  "minecraft:standing_signs",
  "minecraft:stone_bricks",
  "minecraft:stone_buttons",
  "minecraft:stone_ore_replaceables",
  "minecraft:stone_pressure_plates",
  "minecraft:stray_immune_to",
  "minecraft:strider_warm_blocks",
  "minecraft:substrate_overworld",
  "minecraft:sulfur_spike_replaceable_blocks",
  "minecraft:support_override_cactus_flower",
  "minecraft:support_override_snow_layer",
  "minecraft:supports_azalea",
  "minecraft:supports_bamboo",
  "minecraft:supports_big_dripleaf",
  "minecraft:supports_cactus",
  "minecraft:supports_chorus_flower",
  "minecraft:supports_chorus_plant",
  "minecraft:supports_cocoa",
  "minecraft:supports_crimson_fungus",
  "minecraft:supports_crimson_roots",
  "minecraft:supports_crops",
  "minecraft:supports_dry_vegetation",
  "minecraft:supports_frogspawn",
  "minecraft:supports_hanging_mangrove_propagule",
  "minecraft:supports_lily_pad",
  "minecraft:supports_mangrove_propagule",
  "minecraft:supports_melon_stem",
  "minecraft:supports_melon_stem_fruit",
  "minecraft:supports_nether_sprouts",
  "minecraft:supports_nether_wart",
  "minecraft:supports_pumpkin_stem",
  "minecraft:supports_pumpkin_stem_fruit",
  "minecraft:supports_small_dripleaf",
  "minecraft:supports_stem_crops",
  "minecraft:supports_stem_fruit",
  "minecraft:supports_sugar_cane",
  "minecraft:supports_sugar_cane_adjacently",
  "minecraft:supports_vegetation",
  "minecraft:supports_warped_fungus",
  "minecraft:supports_warped_roots",
  "minecraft:supports_wither_rose",
  "minecraft:suppresses_bounce",
  "minecraft:sword_efficient",
  "minecraft:sword_instantly_mines",
  "minecraft:terracotta",
  "minecraft:trail_ruins_replaceable",
  "minecraft:trapdoors",
  "minecraft:triggers_ambient_desert_dry_vegetation_block_sounds",
  "minecraft:triggers_ambient_desert_sand_block_sounds",
  "minecraft:triggers_ambient_dried_ghast_block_sounds",
  "minecraft:underwater_bonemeals",
  "minecraft:unstable_bottom_center",
  "minecraft:valid_spawn",
  "minecraft:vibration_resonators",
  "minecraft:wall_corals",
  "minecraft:wall_hanging_signs",
  "minecraft:wall_post_override",
  "minecraft:wall_signs",
  "minecraft:walls",
  "minecraft:warped_stems",
  "minecraft:wart_blocks",
  "minecraft:wither_immune",
  "minecraft:wither_immune_to",
  "minecraft:wither_skeleton_immune_to",
  "minecraft:wither_summon_base_blocks",
  "minecraft:wolves_spawnable_on",
  "minecraft:wooden_buttons",
  "minecraft:wooden_doors",
  "minecraft:wooden_fences",
  "minecraft:wooden_pressure_plates",
  "minecraft:wooden_shelves",
  "minecraft:wooden_slabs",
  "minecraft:wooden_stairs",
  "minecraft:wooden_trapdoors",
  "minecraft:wool",
  "minecraft:wool_carpets",
] as const;

const EXACT_NAMES: Readonly<Record<string, string>> = {
  "minecraft:air": Messages.src.minecraft.block.tags.text0001,
  "minecraft:anvil": Messages.src.minecraft.block.tags.text0002,
  "minecraft:banners": Messages.src.minecraft.block.tags.text0003,
  "minecraft:bars": Messages.src.minecraft.block.tags.text0004,
  "minecraft:beds": Messages.src.minecraft.block.tags.text0005,
  "minecraft:beehives": Messages.src.minecraft.block.tags.text0006,
  "minecraft:buttons": Messages.src.minecraft.block.tags.text0007,
  "minecraft:campfires": Messages.src.minecraft.block.tags.text0008,
  "minecraft:candles": Messages.src.minecraft.block.tags.text0009,
  "minecraft:cauldrons": Messages.src.minecraft.block.tags.text0010,
  "minecraft:chains": Messages.src.minecraft.block.tags.text0011,
  "minecraft:climbable": Messages.src.minecraft.block.tags.text0012,
  "minecraft:concrete": Messages.src.minecraft.block.tags.text0013,
  "minecraft:concrete_powders": Messages.src.minecraft.block.tags.text0014,
  "minecraft:copper": Messages.src.minecraft.block.tags.text0015,
  "minecraft:coral_blocks": Messages.src.minecraft.block.tags.text0016,
  "minecraft:coral_plants": Messages.src.minecraft.block.tags.text0017,
  "minecraft:corals": Messages.src.minecraft.block.tags.text0018,
  "minecraft:crops": Messages.src.minecraft.block.tags.text0019,
  "minecraft:dirt": Messages.src.minecraft.block.tags.text0020,
  "minecraft:doors": Messages.src.minecraft.block.tags.text0021,
  "minecraft:fence_gates": Messages.src.minecraft.block.tags.text0022,
  "minecraft:fences": Messages.src.minecraft.block.tags.text0023,
  "minecraft:fire": Messages.src.minecraft.block.tags.text0024,
  "minecraft:flower_pots": Messages.src.minecraft.block.tags.text0025,
  "minecraft:flowers": Messages.src.minecraft.block.tags.text0026,
  "minecraft:glazed_terracotta": Messages.src.minecraft.block.tags.text0027,
  "minecraft:grass_blocks": Messages.src.minecraft.block.tags.text0028,
  "minecraft:ice": Messages.src.minecraft.block.tags.text0029,
  "minecraft:impermeable": Messages.src.minecraft.block.tags.text0030,
  "minecraft:lanterns": Messages.src.minecraft.block.tags.text0031,
  "minecraft:leaves": Messages.src.minecraft.block.tags.text0032,
  "minecraft:lightning_rods": Messages.src.minecraft.block.tags.text0033,
  "minecraft:logs": Messages.src.minecraft.block.tags.text0034,
  "minecraft:logs_that_burn": Messages.src.minecraft.block.tags.text0035,
  "minecraft:moss_blocks": Messages.src.minecraft.block.tags.text0036,
  "minecraft:mud": Messages.src.minecraft.block.tags.text0037,
  "minecraft:nylium": Messages.src.minecraft.block.tags.text0038,
  "minecraft:planks": Messages.src.minecraft.block.tags.text0039,
  "minecraft:portals": Messages.src.minecraft.block.tags.text0040,
  "minecraft:pressure_plates": Messages.src.minecraft.block.tags.text0041,
  "minecraft:rails": Messages.src.minecraft.block.tags.text0042,
  "minecraft:replaceable": Messages.src.minecraft.block.tags.text0043,
  "minecraft:sand": Messages.src.minecraft.block.tags.text0044,
  "minecraft:saplings": Messages.src.minecraft.block.tags.text0045,
  "minecraft:shulker_boxes": Messages.src.minecraft.block.tags.text0046,
  "minecraft:signs": Messages.src.minecraft.block.tags.text0047,
  "minecraft:slabs": Messages.src.minecraft.block.tags.text0048,
  "minecraft:small_flowers": Messages.src.minecraft.block.tags.text0049,
  "minecraft:snow": Messages.src.minecraft.block.tags.text0050,
  "minecraft:stairs": Messages.src.minecraft.block.tags.text0051,
  "minecraft:stone_bricks": Messages.src.minecraft.block.tags.text0052,
  "minecraft:terracotta": Messages.src.minecraft.block.tags.text0053,
  "minecraft:trapdoors": Messages.src.minecraft.block.tags.text0054,
  "minecraft:wall_corals": Messages.src.minecraft.block.tags.text0055,
  "minecraft:wall_signs": Messages.src.minecraft.block.tags.text0056,
  "minecraft:walls": Messages.src.minecraft.block.tags.text0057,
  "minecraft:wart_blocks": Messages.src.minecraft.block.tags.text0058,
  "minecraft:wool": Messages.src.minecraft.block.tags.text0059,
  "minecraft:wool_carpets": Messages.src.minecraft.block.tags.text0060,
};

const TOOL_NAMES: Readonly<Record<string, string>> = {
  axe: Messages.src.minecraft.block.tags.text0061,
  hoe: Messages.src.minecraft.block.tags.text0062,
  pickaxe: Messages.src.minecraft.block.tags.text0063,
  shovel: Messages.src.minecraft.block.tags.text0064,
  wooden: Messages.src.minecraft.block.tags.text0065,
  stone: Messages.src.minecraft.block.tags.text0066,
  copper: Messages.src.minecraft.block.tags.text0067,
  iron: Messages.src.minecraft.block.tags.text0068,
  gold: Messages.src.minecraft.block.tags.text0069,
  diamond: Messages.src.minecraft.block.tags.text0070,
  netherite: Messages.src.minecraft.block.tags.text0071,
};

const WOOD_NAMES: Readonly<Record<string, string>> = {
  acacia: Messages.src.minecraft.block.tags.text0072,
  birch: Messages.src.minecraft.block.tags.text0073,
  cherry: Messages.src.minecraft.block.tags.text0074,
  crimson: Messages.src.minecraft.block.tags.text0075,
  dark_oak: Messages.src.minecraft.block.tags.text0076,
  jungle: Messages.src.minecraft.block.tags.text0077,
  mangrove: Messages.src.minecraft.block.tags.text0078,
  oak: Messages.src.minecraft.block.tags.text0079,
  pale_oak: Messages.src.minecraft.block.tags.text0080,
  spruce: Messages.src.minecraft.block.tags.text0081,
  warped: Messages.src.minecraft.block.tags.text0082,
};

function translatedName(id: string): string {
  const exact = EXACT_NAMES[id];
  if (exact) return exact;
  const path = id.slice("minecraft:".length);
  if (path.startsWith("mineable/")) {
    return Messages.src.minecraft.block.tags.text0083(
      TOOL_NAMES[path.slice("mineable/".length)] ??
        path.slice("mineable/".length),
    );
  }
  if (path.startsWith("needs_") && path.endsWith("_tool")) {
    const tool = path.slice("needs_".length, -"_tool".length);
    return Messages.src.minecraft.block.tags.text0084(TOOL_NAMES[tool] ?? tool);
  }
  if (path.startsWith("incorrect_for_") && path.endsWith("_tool")) {
    const tool = path.slice("incorrect_for_".length, -"_tool".length);
    return Messages.src.minecraft.block.tags.text0085(TOOL_NAMES[tool] ?? tool);
  }
  if (path.endsWith("_logs")) {
    const wood = path.slice(0, -"_logs".length);
    return Messages.src.minecraft.block.tags.text0086(WOOD_NAMES[wood] ?? wood);
  }
  if (path.endsWith("_ores"))
    return Messages.src.minecraft.block.tags.text0087(
      path.slice(0, -"_ores".length).replaceAll("_", " "),
    );
  if (path.endsWith("_spawnable_on"))
    return Messages.src.minecraft.block.tags.text0088(
      path.slice(0, -"_spawnable_on".length).replaceAll("_", " "),
    );
  if (path.startsWith("supports_"))
    return Messages.src.minecraft.block.tags.text0089(
      path.slice("supports_".length).replaceAll("_", " "),
    );
  if (path.includes("replaceable"))
    return Messages.src.minecraft.block.tags.text0090(
      path.replaceAll("_", " "),
    );
  if (path.includes("immune"))
    return Messages.src.minecraft.block.tags.text0091(
      path.replaceAll("_", " "),
    );
  if (path.includes("sound"))
    return Messages.src.minecraft.block.tags.text0092(
      path.replaceAll("_", " "),
    );
  return Messages.src.minecraft.block.tags.text0093(path.replaceAll("_", " "));
}

export const VANILLA_BLOCK_TAG_DETAILS: Readonly<Record<string, string>> =
  Object.fromEntries(
    VANILLA_BLOCK_TAGS.map((id) => [
      id,
      Messages.src.minecraft.block.tags.text0094(translatedName(id)),
    ]),
  );
