import {
  CRAFTENGINE_MINIMESSAGE_TAGS,
  STANDARD_MINIMESSAGE_TAGS,
} from "./parser.js";

import { Messages } from "../../messages.js";

export interface MiniMessageCompletionDefinition {
  readonly tag: string;
  readonly detail: string;
  readonly snippet: string;
}

const DETAILS: Readonly<Record<string, string>> = {
  black: Messages.src.text.minimessage.completions.text0001,
  dark_blue: Messages.src.text.minimessage.completions.text0002,
  dark_green: Messages.src.text.minimessage.completions.text0003,
  dark_aqua: Messages.src.text.minimessage.completions.text0004,
  dark_red: Messages.src.text.minimessage.completions.text0005,
  dark_purple: Messages.src.text.minimessage.completions.text0006,
  gold: Messages.src.text.minimessage.completions.text0007,
  gray: Messages.src.text.minimessage.completions.text0008,
  dark_gray: Messages.src.text.minimessage.completions.text0009,
  blue: Messages.src.text.minimessage.completions.text0010,
  green: Messages.src.text.minimessage.completions.text0011,
  aqua: Messages.src.text.minimessage.completions.text0012,
  red: Messages.src.text.minimessage.completions.text0013,
  light_purple: Messages.src.text.minimessage.completions.text0014,
  yellow: Messages.src.text.minimessage.completions.text0015,
  white: Messages.src.text.minimessage.completions.text0016,
  color: Messages.src.text.minimessage.completions.text0017,
  c: Messages.src.text.minimessage.completions.text0018,
  bold: Messages.src.text.minimessage.completions.text0019,
  b: Messages.src.text.minimessage.completions.text0020,
  italic: Messages.src.text.minimessage.completions.text0021,
  em: Messages.src.text.minimessage.completions.text0022,
  i: Messages.src.text.minimessage.completions.text0023,
  underlined: Messages.src.text.minimessage.completions.text0024,
  u: Messages.src.text.minimessage.completions.text0025,
  strikethrough: Messages.src.text.minimessage.completions.text0026,
  st: Messages.src.text.minimessage.completions.text0027,
  obfuscated: Messages.src.text.minimessage.completions.text0028,
  obf: Messages.src.text.minimessage.completions.text0029,
  reset: Messages.src.text.minimessage.completions.text0030,
  newline: Messages.src.text.minimessage.completions.text0031,
  br: Messages.src.text.minimessage.completions.text0032,
  gradient: Messages.src.text.minimessage.completions.text0033,
  transition: Messages.src.text.minimessage.completions.text0034,
  rainbow: Messages.src.text.minimessage.completions.text0035,
  pride: Messages.src.text.minimessage.completions.text0036,
  click: Messages.src.text.minimessage.completions.text0037,
  hover: Messages.src.text.minimessage.completions.text0038,
  insertion: Messages.src.text.minimessage.completions.text0039,
  font: Messages.src.text.minimessage.completions.text0040,
  keybind: Messages.src.text.minimessage.completions.text0041,
  selector: Messages.src.text.minimessage.completions.text0042,
  score: Messages.src.text.minimessage.completions.text0043,
  nbt: Messages.src.text.minimessage.completions.text0044,
  shadow_color: Messages.src.text.minimessage.completions.text0045,
  sprite: Messages.src.text.minimessage.completions.text0046,
  head: Messages.src.text.minimessage.completions.text0047,
  lang: Messages.src.text.minimessage.completions.text0048,
  translate: Messages.src.text.minimessage.completions.text0049,
  tr: Messages.src.text.minimessage.completions.text0050,
  lang_or: Messages.src.text.minimessage.completions.text0051,
  translate_or: Messages.src.text.minimessage.completions.text0052,
  tr_or: Messages.src.text.minimessage.completions.text0053,
  shift: Messages.src.text.minimessage.completions.text0054,
  image: Messages.src.text.minimessage.completions.text0055,
  i18n: Messages.src.text.minimessage.completions.text0056,
  l10n: Messages.src.text.minimessage.completions.text0057,
  arg: Messages.src.text.minimessage.completions.text0058,
  viewer_arg: Messages.src.text.minimessage.completions.text0059,
  papi: Messages.src.text.minimessage.completions.text0060,
  viewer_papi: Messages.src.text.minimessage.completions.text0061,
  rel_papi: Messages.src.text.minimessage.completions.text0062,
  expr: Messages.src.text.minimessage.completions.text0063,
  global: Messages.src.text.minimessage.completions.text0064,
  background: Messages.src.text.minimessage.completions.text0065,
  bubble: Messages.src.text.minimessage.completions.text0066,
  nameplate: Messages.src.text.minimessage.completions.text0067,
};

const SNIPPETS: Readonly<Record<string, string>> = {
  color: "color:${1:#ffffff}>${0}</color>",
  c: "c:${1:#ffffff}>${0}</c>",
  gradient: "gradient:${1:#ffffff}:${2:#000000}>${0}</gradient>",
  transition: "transition:${1:#ffffff}:${2:#000000}:${3:0}>${0}</transition>",
  rainbow: "rainbow:${1:0}>${0}</rainbow>",
  pride: "pride:${1:pride}>${0}</pride>",
  click:
    "click:${1|run_command,suggest_command,open_url,copy_to_clipboard|}:'${2}'>${0}</click>",
  hover: "hover:show_text:'${1}'>${0}</hover>",
  insertion: "insertion:'${1}'>${0}</insertion>",
  font: "font:${1:minecraft:default}>${0}</font>",
  keybind: "keybind:${1:key.jump}>",
  selector: "selector:${1:@s}>",
  score: "score:${1:name}:${2:objective}>",
  nbt: "nbt:${1:path}:${2|block,entity,storage|}:${3}>",
  shadow_color: "shadow_color:${1:#00000080}>${0}</shadow_color>",
  sprite: "sprite:${1:minecraft:atlas}:${2:sprite}>",
  head: "head:${1:ChengZhiYa}>",
  lang: "lang:${1:translation.key}>",
  translate: "translate:${1:translation.key}>",
  tr: "tr:${1:translation.key}>",
  lang_or: Messages.src.text.minimessage.completions.text0068,
  translate_or: Messages.src.text.minimessage.completions.text0069,
  tr_or: Messages.src.text.minimessage.completions.text0070,
  shift: "shift:${1:0}>",
  image: "image:${1:namespace:id}>",
  i18n: "i18n:${1:translation.key}>",
  l10n: "l10n:${1:translation.key}>",
  arg: "arg:${1:0}>",
  viewer_arg: "viewer_arg:${1:name}>",
  papi: "papi:${1:placeholder}>",
  viewer_papi: "viewer_papi:${1:placeholder}>",
  rel_papi: "rel_papi:${1:placeholder}>",
  expr: "expr:'${1:0.00}':'${2:1 + 1}'>",
  global: "global:${1:name}>",
  background: Messages.src.text.minimessage.completions.text0071,
  bubble: Messages.src.text.minimessage.completions.text0072,
  nameplate: Messages.src.text.minimessage.completions.text0073,
  newline: "newline>",
  br: "br>",
  reset: "reset>",
};

const DECORATIONS = new Set([
  "black",
  "dark_blue",
  "dark_green",
  "dark_aqua",
  "dark_red",
  "dark_purple",
  "gold",
  "gray",
  "dark_gray",
  "blue",
  "green",
  "aqua",
  "red",
  "light_purple",
  "yellow",
  "white",
  "bold",
  "b",
  "italic",
  "em",
  "i",
  "underlined",
  "u",
  "strikethrough",
  "st",
  "obfuscated",
  "obf",
]);

export const MINI_MESSAGE_COMPLETIONS: readonly MiniMessageCompletionDefinition[] =
  [
    ...STANDARD_MINIMESSAGE_TAGS,
    ...CRAFTENGINE_MINIMESSAGE_TAGS,
    "!bold",
    "!b",
    "!italic",
    "!em",
    "!i",
    "!underlined",
    "!u",
    "!strikethrough",
    "!st",
    "!obfuscated",
    "!obf",
  ].map((tag) => {
    if (tag.startsWith("!")) {
      return {
        tag,
        detail: Messages.src.text.minimessage.completions.text0074(
          DETAILS[tag.slice(1)]?.replace(
            Messages.src.text.minimessage.completions.text0076,
            "",
          ) ?? Messages.src.text.minimessage.completions.text0001,
        ),
        snippet: `${tag}>`,
      };
    }
    return {
      tag,
      detail: DETAILS[tag] ?? Messages.src.text.minimessage.completions.text0075,
      snippet:
        SNIPPETS[tag] ??
        (DECORATIONS.has(tag) ? `${tag}>\${0}</${tag}>` : `${tag}>`),
    };
  });
